### ISSUE TITLE
Typo in chapter 2.4 in the provided pdf

### ISSUE THREAD

**Issue by TKW25** [laboon/ebook#135] opened 2018-01-08 22:00 UTC
"Function" is spelled incorrectly in the following sentence in chapter 2.4 of the provided pdf: 
"It is important to note that it would be literally impossible to perform exhaustive testing (testing
every combination of input) on this functio."

**Comment by timparenti** [comment] 2018-01-08 22:08
Duplicate of #131, fixed in #132.

**Closed** 2018-01-19 00:42 UTC
